# Generated by Django 3.1.1 on 2020-10-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeimage',
            name='user',
        ),
    ]
